version: '3.8'

services:
  db:
    image: mysql
    restart: always
    container_name: mysql-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USERNAME: root
      MYSQL_DATABASE: mysql-db
#    volumes:
#      - ./data.sql:/docker-entrypoint-init.db.d/data.sql